language: generic
sudo: false
before_install:
  - export PATH="$HOME/.cask/bin:$HOME/.evm/bin:$PATH"
  - git clone https://github.com/rejeep/evm.git "$HOME/.evm"
  - evm config path /tmp
  - evm install $EVM_EMACS --use --skip
  - curl -fsSkL https://raw.github.com/cask/cask/master/go | python
install: cask
script: cask exec buttercup -L . -L tests
env:
  matrix:
    - EVM_EMACS=emacs-24.4-travis
    - EVM_EMACS=emacs-24.5-travis
    - EVM_EMACS=emacs-25-pre-travis
    - EVM_EMACS=emacs-git-snapshot-travis
